language: python
sudo: false
python:
  - "2.7"
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls
  - travis_retry python setup.py develop
script: nosetests --with-coverage --cover-package=qelos
after_success:
  - coveralls
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
notifications:
  slack: eisbonn:qosRnEbOef7JTnLqe8hf3rP7
  email: false